### ISSUE TITLE
Videos not loading

### ISSUE THREAD

**Issue by frostedtips** [cs50/roku50#3]
Hello CS50!
I've been trying to use your Roku channel off and on for a few months but every time I attempt to watch a video, I'm unable to. I can see the categories for the videos, like CS50Live and years from 2017 down to 2010, but when I attempt to access any of the lectures, sections, walkthroughs, etc, none appear. I get a message that reads 'Retrieving...' but nothing more - it just keeps that same message and doesn't load the videos. I can attempt to go back up the app's navigation and try different sections, but none work, and even the 'Retrieiving...' message disappears. Do you know what the problem could be?
Thank you!

**Comment by coltonoscopy** [comment]
Hi @frostedtips, so sorry for the inconvenience! It was an SSL-related issue on our end as we've begun deploying the new version of our app and migrating our server to use HTTPS by default, but it's fixed now! Be on the lookout for a new version in the coming weeks as well :)
